#!/bin/bash
# sort system info from <hostname>-info directory generated by info.sh


# requires
# dmidecode
# WARNING!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 
# If number of hardware is greater than 1, only the 1st info gets by this script.
# The first CPU information, first memory information, etc.



INFODIR=$1

getinfo()
{

  local names="bios-vendor
    bios-version
    bios-release-date
    system-manufacturer
    system-product-name
    system-version
    system-serial-number
    system-uuid
    baseboard-manufacturer
    baseboard-product-name
    baseboard-version
    baseboard-serial-number
    baseboard-asset-tag
    chassis-manufacturer
    chassis-type
    chassis-version
    chassis-serial-number
    chassis-asset-tag
    processor-family
    processor-manufacturer
    processor-version
    processor-frequency"

  if [ -f $INFODIR/dmidecode.bin ]; then
    for i in $names
      do
        a=$(dmidecode -s $i -u --from-dump $INFODIR/dmidecode.bin |grep -v ^#| head -n 1)
        eval ${i//-/_}=\"$a\"
      done
    
  elif [ -f $INFODIR/dmidecode ]; then
    bios_vendor=$(grep -A 3 "BIOS Information" $INFODIR/dmidecode | grep Vendor | awk -F ": " '{print $2}')
    bios_version=$(grep -A 3 "BIOS Information" $INFODIR/dmidecode | grep Version |awk -F ": " '{print $2}')
    bios_release_date=$(grep -A 3 "BIOS Information" $INFODIR/dmidecode | grep "Release Date" | awk -F ": " '{print $2}')
    system_manufacturer=$(grep -A 4 "System Information" $INFODIR/dmidecode | grep "Manufacturer" |awk -F ": " '{print $2}')
    system_product_name=$(grep -A 4 "System Information" $INFODIR/dmidecode | grep "Product Name" |awk -F ": " '{print $2}')
    system_version=$(grep -A 4 "System Information" $INFODIR/dmidecode | grep "Version" |awk -F ": " '{print $2}')
    system_serial_number=$(grep -A 4 "System Information" $INFODIR/dmidecode | grep "Serial Number" | awk -F ": " '{print $2}')
    system_uuid=$(grep -A 5 "System Information" $INFODIR/dmidecode | grep "UUID" | awk -F ": " '{print $2}')
    baseboard_manufacturer=$(grep -A 4 "Base Board Information" $INFODIR/dmidecode | grep "Manufacturer" | awk -F ": " '{print $2}')
    baseboard_product_name=$(grep -A 4 "Base Board Information" $INFODIR/dmidecode | grep "Product Name" | awk -F ": " '{print $2}')
    baseboard_version=$(grep -A 5 "Base Board Information" $INFODIR/dmidecode | grep "Version" | awk -F ": " '{print $2}')
    baseboard_serial_number=$(grep -A 4 "Base Board Information" $INFODIR/dmidecode | grep "Serial Number" | awk -F ": " '{print $2}')
    baseboard_asset_tag=$(grep -A 4 "Base Board Information" $INFODIR/dmidecode | grep "Asset Tag" | awk -F ": " '{print $2}')
    chassis_manufacturer=$(grep -A 6 "Chassis Information" $INFODIR/dmidecode | grep "Manufacturer" | awk -F ": " '{print $2}')
    chassis_type=$(grep -A 6 "Chassis Information" $INFODIR/dmidecode | grep "Type" | awk -F ": " '{print $2}')
    chassis_version=$(grep -A 6 "Chassis Information" $INFODIR/dmidecode | grep "Version" | awk -F ": " '{print $2}')
    chassis_serial_number=$(grep -A 6 "Chassis Information" $INFODIR/dmidecode | grep "Serial Number" | awk -F ": " '{print $2}')
    chassis_asset_tag=$(grep -A 6 "Chassis Information" $INFODIR/dmidecode | grep "Asset Tag" | awk -F ": " '{print $2}')
    processor_family=$(grep -A 9 "Processor Information" $INFODIR/dmidecode | grep "Family" | head -n 1 | awk -F ": " '{print $2}')
    processor_manufacturer=$(grep -A 9 "Processor Information" $INFODIR/dmidecode | grep "Manufacturer" | head -n 1 | awk -F ": " '{print $2}')
    processor_version=$(grep -A 9 "Processor Information" $INFODIR/dmidecode | grep "Version" | head -n 1 | awk -F ": " '{print $2}')
    processor_frequency=$(grep -A 9 "Processor Information" $INFODIR/dmidecode | grep "Max Speed" | head -n 1 | awk -F ": " '{print $2}')
  else
    for i in $names
      do
        eval ${i//-/_}=
      done
  fi
  pcpu_count=$(grep "Processor Information" $INFODIR/dmidecode | wc -l)
  lcpu_count=$(grep "^CPU(s)" $INFODIR/lscpu | awk '{print $NF}')
#  memory=$(grep "Memory Device" isoft-212-info/dmidecode -A 10 | grep Size | grep -v "No Module Installed" | cut -d " " -f 2)
  mem_count=$(grep -A 10 "Memory Device$" $INFODIR/dmidecode | grep "Size:" | grep -v "No Module Installed" | wc -l)
  mem_size=$(grep -A 10 "Memory Device$" $INFODIR/dmidecode | grep "Size:" | grep -v "No Module Installed"  | head -n 1 | awk -F ": " '{print $2}')
  mem_type=$(grep -A 10 "Memory Device$" $INFODIR/dmidecode | grep "Type:" | grep -v "Unknown"  | head -n 1 | awk -F ": " '{print $2}')
  mem_frequency=$(grep -A 20 "Memory Device$" $INFODIR/dmidecode | grep "Speed:" | grep -v "Unknown"  | head -n 1 | awk -F ": " '{print $2}')
  
}



showinfo()
{
  getinfo

  echo System Information Reporter
  echo
  echo Summary
  echo -e "Vendor:\t$bios_vendor"
  echo -e "Model:\t$system_product_name"
  echo -e "Platform:\t$(cat $INFODIR/arch 2>/dev/null)"
  echo
  echo CPU
  echo -e "Vendor:\t$processor_manufacturer"
  echo -e "Family:\t$processor_family"
  echo -e "Version:\t$processor_version"
  echo -e "Frequency:\t$processor_frequency"
  echo -e "Pysic CPUs:\t$pcpu_count"
  echo -e "Logic CPUs:\t$lcpu_count"
  echo
  echo Memory
  echo -e "Type:\t$mem_type"
  echo -e "Frequency:\t$mem_frequency"
  echo -e "Size:\t$mem_count*$mem_size"
  echo
  echo Base board
  echo -e "Vendor:\t$baseboard_manufacturer"
  echo -e "Model:\t$baseboard_product_name"
  echo -e "Version:\t$baseboard_version"
  echo 
  echo BIOS
  echo -e "Vendor:\t$bios_vendor"
  echo -e "Version:\t$bios_version"
  echo
  


}



showinfo
